const mockTasks = [
    {
        id: "1",
        title: "Design new landing page",
        description:
            "Create mockups for the new product landing page with updated branding",
        status: "todo",
        priority: "high" as const,
        assignee: {
            name: "Emma Wilson",
            avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Emma",
        },
        dueDate: "Oct 30",
        workspace: "Product Team",
        project: "Website Redesign",
        tags: ["Design", "Marketing"],
        comments: 3,
        attachments: 2,
    },
    {
        id: "2",
        title: "Update API documentation",
        description: "Add documentation for the new authentication endpoints",
        status: "todo",
        priority: "medium" as const,
        assignee: {
            name: "Michael Chen",
            avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Michael",
        },
        dueDate: "Nov 2",
        workspace: "Engineering",
        project: "API Platform",
        tags: ["Documentation"],
        comments: 1,
        attachments: 0,
    },
    {
        id: "3",
        title: "Implement user authentication",
        description: "Add OAuth 2.0 support and JWT token handling",
        status: "in-progress",
        priority: "urgent" as const,
        assignee: {
            name: "David Kim",
            avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=David",
        },
        dueDate: "Oct 28",
        workspace: "Engineering",
        project: "Authentication System",
        tags: ["Backend", "Security"],
        comments: 8,
        attachments: 3,
    },
    {
        id: "4",
        title: "Mobile app testing",
        description: "Test new features on iOS and Android devices",
        status: "in-progress",
        priority: "high" as const,
        assignee: {
            name: "Sarah Anderson",
            avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah",
        },
        dueDate: "Oct 29",
        workspace: "Product Team",
        project: "Mobile App Q4",
        tags: ["QA", "Mobile"],
        comments: 5,
        attachments: 1,
    },
    {
        id: "5",
        title: "Code review for payment flow",
        description:
            "Review and approve changes to the payment processing system",
        status: "review",
        priority: "high" as const,
        assignee: {
            name: "Alex Turner",
            avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Alex",
        },
        dueDate: "Oct 27",
        workspace: "Engineering",
        project: "Payment Integration",
        tags: ["Backend", "Payments"],
        comments: 12,
        attachments: 0,
    },
    {
        id: "6",
        title: "Update user profile UI",
        description: "Redesigned profile page with new layout and features",
        status: "done",
        priority: "medium" as const,
        assignee: {
            name: "Sophie Martinez",
            avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sophie",
        },
        dueDate: "Oct 25",
        workspace: "Product Team",
        project: "User Experience Refresh",
        tags: ["Frontend", "UI"],
        comments: 6,
        attachments: 4,
    },
    {
        id: "7",
        title: "Create analytics dashboard",
        description:
            "Build comprehensive analytics dashboard for business insights",
        status: "in-progress",
        priority: "medium" as const,
        assignee: {
            name: "Lisa Rodriguez",
            avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Lisa",
        },
        dueDate: "Nov 5",
        workspace: "Marketing",
        project: "Analytics Platform",
        tags: ["Analytics", "Dashboard"],
        comments: 2,
        attachments: 1,
    },
    {
        id: "8",
        title: "Database migration",
        description: "Migrate database to new infrastructure",
        status: "done",
        priority: "high" as const,
        assignee: {
            name: "Chris Lee",
            avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Chris",
        },
        dueDate: "Oct 24",
        workspace: "Engineering",
        project: "Infrastructure Upgrade",
        tags: ["Backend", "Database"],
        comments: 2,
        attachments: 1,
    },
    {
        id: "9",
        title: "Email campaign setup",
        description:
            "Configure automated email sequences for customer onboarding",
        status: "todo",
        priority: "low" as const,
        assignee: {
            name: "Jordan Taylor",
            avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jordan",
        },
        dueDate: "Nov 8",
        workspace: "Marketing",
        project: "Email Marketing",
        tags: ["Marketing", "Email"],
        comments: 0,
        attachments: 0,
    },
    {
        id: "10",
        title: "Customer onboarding flow",
        description: "Design and implement new user onboarding experience",
        status: "in-progress",
        priority: "urgent" as const,
        assignee: {
            name: "Maya Patel",
            avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Maya",
        },
        dueDate: "Oct 26",
        workspace: "Product Team",
        project: "User Experience Refresh",
        tags: ["UX", "Frontend"],
        comments: 15,
        attachments: 5,
    },
    {
        id: "11",
        title: "Performance optimization",
        description: "Optimize application performance and reduce load times",
        status: "review",
        priority: "high" as const,
        assignee: {
            name: "Ryan Cooper",
            avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ryan",
        },
        dueDate: "Nov 1",
        workspace: "Engineering",
        project: "Performance Improvements",
        tags: ["Performance", "Backend"],
        comments: 4,
        attachments: 2,
    },
    {
        id: "12",
        title: "Social media integration",
        description: "Integrate social media sharing features",
        status: "todo",
        priority: "low" as const,
        assignee: {
            name: "Anna Foster",
            avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Anna",
        },
        dueDate: "Nov 12",
        workspace: "Marketing",
        project: "Social Campaign",
        tags: ["Social Media", "Integration"],
        comments: 1,
        attachments: 0,
    },
];

const statusConfig = {
    todo: { label: "To Do", color: "bg-gray-500", dotColor: "bg-gray-500" },
    "in-progress": {
        label: "In Progress",
        color: "bg-blue-500",
        dotColor: "bg-blue-500",
    },
    review: {
        label: "Review",
        color: "bg-yellow-500",
        dotColor: "bg-yellow-500",
    },
    done: { label: "Done", color: "bg-green-500", dotColor: "bg-green-500" },
};

const priorityConfig = {
    urgent: { label: "Urgent", variant: "destructive" as const },
    high: { label: "High", variant: "default" as const },
    medium: { label: "Medium", variant: "secondary" as const },
    low: { label: "Low", variant: "outline" as const },
};
